# 端口号
server:
  port: 80


spring:
  # thymeleaf配置
  thymeleaf:
    enabled: true
    encoding: UTF-8
    mode: HTML
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
    suffix: .html

#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/user?useUnicode=true&characterEncoding=utf8&useSSL=false
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: 123456
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO


